const nodes = [
              { id: "A", label: "Core Module" },
              { id: "B", label: "Auth Service" },
              { id: "C", label: "User API" },
              { id: "D", label: "Frontend" },
              { id: "E", label: "Database" },
              { id: "F", label: "Cache" },
              { id: "G", label: "Logging Service" },
              { id: "H", label: "Analytics Service" },
              { id: "I", label: "Notification Service" },
              { id: "J", label: "Payment Gateway" },
              { id: "K", label: "Email Service" },
              { id: "L", label: "Search Service" },
              { id: "M", label: "Recommendation Engine" },
              { id: "N", label: "Monitoring Service" },
              { id: "O", label: "Admin Dashboard" },
              { id: "P", label: "External API Integration" }
            ]
const edges=[
              { source: "A", target: "B" },
              { source: "A", target: "C" },
              { source: "B", target: "D" },
              { source: "C", target: "D" },
              { source: "C", target: "E" },
              { source: "C", target: "F" },
              { source: "B", target: "E" },
              { source: "A", target: "G" },
              { source: "D", target: "H" },
              { source: "C", target: "I" },
              { source: "D", target: "I" },
              { source: "J", target: "C" },
              { source: "D", target: "J" },
              { source: "K", target: "I" },
              { source: "L", target: "C" },
              { source: "M", target: "L" },
              { source: "M", target: "D" },
              { source: "N", target: "A" },
              { source: "N", target: "E" },
              { source: "O", target: "B" },
              { source: "O", target: "E" },
              { source: "P", target: "C" },
              { source: "P", target: "J" },
            ]